export const ErrorCode = {
  MEMEX_DB_CONNECTION_FAILED: 'MEMEX_DB_CONNECTION_FAILED',
  MEMEX_AUTH_NO_SESSION: 'MEMEX_AUTH_NO_SESSION',
  MEMEX_OAUTH_EXCHANGE_FAILED: 'MEMEX_OAUTH_EXCHANGE_FAILED',
  MEMEX_TOKEN_DECRYPT_FAILED: 'MEMEX_TOKEN_DECRYPT_FAILED',
  MEMEX_CONNECTOR_NOT_IMPLEMENTED: 'MEMEX_CONNECTOR_NOT_IMPLEMENTED',
  MEMEX_ENV_INVALID: 'MEMEX_ENV_INVALID',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
