export const ErrorCode = {
  HOLO_DB_CONNECTION_FAILED: 'HOLO_DB_CONNECTION_FAILED',
  HOLO_AUTH_NO_SESSION: 'HOLO_AUTH_NO_SESSION',
  HOLO_AUTH_NO_ACTIVE_ORG: 'HOLO_AUTH_NO_ACTIVE_ORG',
  HOLO_AUTH_FORBIDDEN: 'HOLO_AUTH_FORBIDDEN',
  HOLO_AUTH_NOT_ALLOWLISTED: 'HOLO_AUTH_NOT_ALLOWLISTED',
  HOLO_OAUTH_EXCHANGE_FAILED: 'HOLO_OAUTH_EXCHANGE_FAILED',
  HOLO_OAUTH_CODE_INVALID: 'HOLO_OAUTH_CODE_INVALID',
  HOLO_TOKEN_DECRYPT_FAILED: 'HOLO_TOKEN_DECRYPT_FAILED',
  HOLO_CONNECTOR_NOT_IMPLEMENTED: 'HOLO_CONNECTOR_NOT_IMPLEMENTED',
  HOLO_ENV_INVALID: 'HOLO_ENV_INVALID',
  HOLO_ALLOWLIST_EMPTY: 'HOLO_ALLOWLIST_EMPTY',
  HOLO_ALLOWLIST_OVERSIZED: 'HOLO_ALLOWLIST_OVERSIZED',
  HOLO_INGESTION_RATE_LIMITED: 'HOLO_INGESTION_RATE_LIMITED',
  HOLO_INVALID_INPUT: 'HOLO_INVALID_INPUT',
  HOLO_INTERNAL: 'HOLO_INTERNAL',
  HOLO_NOT_FOUND: 'HOLO_NOT_FOUND',
  HOLO_ARTIFACT_NOT_FOUND: 'HOLO_ARTIFACT_NOT_FOUND',
  HOLO_SYNC_CANCELLED: 'HOLO_SYNC_CANCELLED',
  // Slack
  HOLO_SLACK_BOT_NOT_INVITED: 'HOLO_SLACK_BOT_NOT_INVITED',
  // Notion
  HOLO_NOTION_TOKEN_INVALID: 'HOLO_NOTION_TOKEN_INVALID',
  HOLO_NOTION_PAGE_NOT_FOUND: 'HOLO_NOTION_PAGE_NOT_FOUND',
  // Pylon
  HOLO_PYLON_KEY_INVALID: 'HOLO_PYLON_KEY_INVALID',
  // Airtable
  HOLO_AIRTABLE_TOKEN_INVALID: 'HOLO_AIRTABLE_TOKEN_INVALID',
  // GitHub
  HOLO_GITHUB_TOKEN_INVALID: 'HOLO_GITHUB_TOKEN_INVALID',
  HOLO_GITHUB_REPO_NOT_FOUND: 'HOLO_GITHUB_REPO_NOT_FOUND',
  HOLO_CLONE_FAILED: 'HOLO_CLONE_FAILED',
  HOLO_FETCH_FAILED: 'HOLO_FETCH_FAILED',
  HOLO_GLOB_TOO_BROAD: 'HOLO_GLOB_TOO_BROAD',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
