export const ErrorCode = {
  HOLO_DB_CONNECTION_FAILED: 'HOLO_DB_CONNECTION_FAILED',
  HOLO_AUTH_NO_SESSION: 'HOLO_AUTH_NO_SESSION',
  HOLO_OAUTH_EXCHANGE_FAILED: 'HOLO_OAUTH_EXCHANGE_FAILED',
  HOLO_TOKEN_DECRYPT_FAILED: 'HOLO_TOKEN_DECRYPT_FAILED',
  HOLO_CONNECTOR_NOT_IMPLEMENTED: 'HOLO_CONNECTOR_NOT_IMPLEMENTED',
  HOLO_ENV_INVALID: 'HOLO_ENV_INVALID',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
