import {
  pgTable,
  text,
  timestamp,
  jsonb,
  uuid,
  index,
  uniqueIndex,
  integer,
  smallint,
  doublePrecision,
} from 'drizzle-orm/pg-core';
import { user, organization } from './auth';

/**
 * 👍 / 👎 / correction submitted against a single assistant turn.
 *
 * `answer_id` is generated by the chat orchestrator at the start of each loop
 * and threaded back to the client; the client POSTs feedback referencing it.
 * The denormalized `question`, `answer`, `citations_jsonb`, `coverage_jsonb`
 * payload is kept on the row so the eval-promotion flow doesn't have to walk
 * the chat history (which may be redacted or pruned).
 *
 * Uniqueness: one feedback row per (answer_id, user_id) — re-submitting a
 * rating from the same user for the same answer updates the existing row
 * (idempotent UPSERT in the REST handler) rather than spamming the table.
 */
export const answerFeedback = pgTable(
  'answer_feedback',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organization.id),
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id),
    answerId: uuid('answer_id').notNull(),
    skillSlug: text('skill_slug'),
    /** -1 = thumbs-down, 0 = neutral (correction without a vote), 1 = thumbs-up */
    rating: smallint('rating').notNull(),
    correctionText: text('correction_text'),
    question: text('question').notNull(),
    answer: text('answer').notNull(),
    citationsJsonb: jsonb('citations_jsonb').notNull(),
    coverageJsonb: jsonb('coverage_jsonb').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    orgSkillCreatedIdx: index('answer_feedback_org_skill_created_idx').on(
      t.organizationId,
      t.skillSlug,
      t.createdAt,
    ),
    answerUserUniq: uniqueIndex('answer_feedback_answer_user_uniq').on(t.answerId, t.userId),
  }),
);

/**
 * Promoted feedback row — a structured grading contract the eval harness
 * runs against the live agent. `expected` is a JSON envelope:
 *   { answer_substrings: string[], must_cite: string[] (chunk_ids), must_not_say: string[] }
 * Three deterministic graders read this — see packages/skills/src/eval-harness.
 *
 * Lifecycle: `pending` (drafted but not yet running) → `active` (graded each
 * nightly cron + on demand) → `archived` (parked, no longer scored).
 */
export const evalEntries = pgTable(
  'eval_entries',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organization.id),
    sourceFeedbackId: uuid('source_feedback_id').references(() => answerFeedback.id, {
      onDelete: 'set null',
    }),
    skillSlug: text('skill_slug'),
    question: text('question').notNull(),
    expected: jsonb('expected').notNull(),
    status: text('status', { enum: ['pending', 'active', 'archived'] })
      .notNull()
      .default('pending'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    createdBy: uuid('created_by').references(() => user.id, { onDelete: 'set null' }),
  },
  (t) => ({
    orgSkillStatusIdx: index('eval_entries_org_skill_status_idx').on(
      t.organizationId,
      t.skillSlug,
      t.status,
    ),
  }),
);

/**
 * Roll-up row written by every eval run (nightly + on-demand). The skill
 * detail page reads recent rows for the regression panel: latest pass-rate,
 * sparkline of the last 14 runs, and a drop-warning if the pass-rate has
 * fallen more than 10pp in the trailing 24h.
 */
export const skillEvalRuns = pgTable(
  'skill_eval_runs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organization.id),
    skillSlug: text('skill_slug').notNull(),
    /** 0.0–1.0 — share of grader-pass-or-failed entries that passed. */
    passRate: doublePrecision('pass_rate').notNull(),
    total: integer('total').notNull(),
    passed: integer('passed').notNull(),
    ranAt: timestamp('ran_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    orgSkillRanIdx: index('skill_eval_runs_org_skill_ran_idx').on(
      t.organizationId,
      t.skillSlug,
      t.ranAt,
    ),
  }),
);

/** Shape of the `expected` jsonb column. */
export interface EvalExpected {
  answer_substrings: string[];
  must_cite: string[];
  must_not_say: string[];
}

/**
 * Bridge from a slack bot reply (identified by its message ts) back to the
 * orchestrator-minted `answer_id` and the denormalized question/answer/sources
 * needed to compose an `answer_feedback` row when a slack reaction lands.
 *
 * Without this table, a `reaction_added` event would only know
 * (team, channel, ts) — too little to attribute feedback to the originating
 * agent turn. Storing it at reply-time (one row per bot answer) keeps the
 * reaction handler dependency-free of slack API round-trips.
 *
 * Uniqueness: per-answer (an answer can only be in one place) and
 * per-message (a single ts has at most one bot answer attached).
 */
export const slackAnswerIndex = pgTable(
  'slack_answer_index',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organization.id, { onDelete: 'cascade' }),
    answerId: uuid('answer_id').notNull(),
    slackTeamId: text('slack_team_id').notNull(),
    slackChannel: text('slack_channel').notNull(),
    slackTs: text('slack_ts').notNull(),
    question: text('question').notNull(),
    answer: text('answer').notNull(),
    sourcesJsonb: jsonb('sources_jsonb').notNull().default([]),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    answerIdUniq: uniqueIndex('slack_answer_index_answer_id_uniq').on(t.answerId),
    teamChannelTsUniq: uniqueIndex('slack_answer_index_team_channel_ts_uniq').on(
      t.slackTeamId,
      t.slackChannel,
      t.slackTs,
    ),
  }),
);

/**
 * Google Chat App equivalent of `slackAnswerIndex`. Anchors a Chat-side
 * message we posted back to its agent-minted `answer_id`, so a future
 * reaction (added in a follow-up) can locate the answer and write an
 * `answer_feedback` row. Resource names are Google's stable identifiers:
 *   - `space_name` = "spaces/AAAA…"
 *   - `message_name` = "spaces/AAAA…/messages/BBBB…"
 */
export const googleChatAnswerIndex = pgTable(
  'google_chat_answer_index',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organization.id, { onDelete: 'cascade' }),
    answerId: uuid('answer_id').notNull(),
    spaceName: text('space_name').notNull(),
    messageName: text('message_name').notNull(),
    question: text('question').notNull(),
    answer: text('answer').notNull(),
    sourcesJsonb: jsonb('sources_jsonb').notNull().default([]),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    answerIdUniq: uniqueIndex('google_chat_answer_index_answer_id_uniq').on(t.answerId),
    spaceMessageUniq: uniqueIndex('google_chat_answer_index_space_message_uniq').on(
      t.spaceName,
      t.messageName,
    ),
  }),
);
